### ISSUE TITLE
Can we find a used dish?

### ISSUE THREAD

**Issue by siliconwitch** [frihamnstorget-space-observatory/radio-telescope#3]

**Comment by rohitrathnam** [comment]
Found some at facebook marketplace - https://www.facebook.com/marketplace/item/331085815303120/

**Comment by siliconwitch** [comment]
Great find! I messaged the guy and he said we could pick it up Sunday. It's not heavy, just big

We can ask in the Blivande forum if there's anyone who could help us move it
